config/routes.rb
VaVote::Application.routes.draw do

  # Add localized scope if alternate localizations are present,
  # otherwise directly add unprefixed routes.
  def conditional_scope(localized_route, root_url, &block)
    unless AppConfig['SupportedLocalizations'].blank?
      scope(localized_route, &block)
      get '/' => root_url # Add root_url outside of localized route.
    else
      block.call
    end
  end

  get '/lookup/registration'            => 'lookup#registration'
    
  namespace :api do
    get '/search(.json)' => 'registrations#show', format: 'json'

    namespace :v1, module: nil do
      get '/demo'            => 'voter_reporting#demo', as: 'demo'
      get '/PollingLocation' => 'voter_reporting#polling_location'
      get '/ReportArrive'    => 'voter_reporting#report_arrive'
      get '/ReportComplete'  => 'voter_reporting#report_complete'
      get '/WaitTimeInfo'    => 'voter_reporting#wait_time_info'
    end
  end



  root_url = AppConfig['demo'] ? 'pages#demo_splash' : "pages#front"
  conditional_scope "/:locale", root_url do

    get   '/not_found'                    => 'pages#not_found', as: 'not_found'

    get   '/registration/new/privacy'     => 'pages#privacy', defaults: { path: 'new_registration' }, as: 'new_registration_privacy'
    get   '/registration/edit/privacy'    => 'pages#privacy', defaults: { path: 'edit_registration' }, as: 'edit_registration_privacy'
    get   '/registration/request_absentee/privacy' => 'pages#privacy', defaults: { path: 'request_absentee_registration' }, as: 'request_absentee_registration_privacy'
    get   '/register/residential/privacy' => 'pages#privacy', defaults: { path: 'register_residential' }, as: 'register_residential_privacy'
    get   '/register/overseas/privacy'    => 'pages#privacy', defaults: { path: 'register_overseas' }, as: 'register_overseas_privacy'

    get   '/search'                       => 'search#new', as: 'search_form'
    get   '/search/unavailable'           => 'search#unavailable'
    post  '/search'                       => 'search#create', as: 'search'

    get   '/register/residential'         => 'registrations#new', defaults: { residence: 'in' }, as: 'register_residential'
    get   '/register/overseas'            => 'registrations#new', defaults: { residence: 'outside' }, as: 'register_overseas'

    get   '/status'                       => 'status#show', as: 'status'
    post  '/status'                       => 'status#search'

    resource :page, only: [], path: '' do
      member do
        get :front, path: AppConfig['demo'] ? '/front' : ''
        get :help
        get :about
        get :about_update_absentee
        get :contact
        get :faq
        get :elections
        get :security
        get :feedback
        get :about_registration
        get :about_update_absentee
        get :online_ballot_marking
        AppConfig.fetch('HeaderLinks', []).each do |settings|
          get settings["url"]
        end
      end
    end

    resource :registration, except: :destroy do
      get '/edit' => 'registrations#edit'
      get '/request_absentee' => 'registrations#edit', defaults: { request_absentee: true }, as: 'request_absentee'
    end
    resource :absentee_request, only: [:new, :create, :edit, :update] do
      get '/not_available' => 'absentee_requests#not_available'
    end
    get '/voter_card.pdf' => 'voter_cards#show', format: 'pdf', as: 'voter_card'


    get '/lookup/absentee_status_history' => 'lookup#absentee_status_history'
    get '/lookup/my_ballot'               => 'lookup#my_ballot'

    get '/ballot_info/:election_uid'      => 'ballot_info#show', as: 'ballot_info'

    resource :form, only: [] do
      member do
        get :request_absentee_status
      end
    end


    root to: root_url
  end
    
  
  match '*unmatched_route', :to => 'application#raise_not_found!'
  
end

app/controllers/status_controller.rb
class StatusController < ApplicationController

  layout 'mobile'

  # shows the status
  def show
    @registration = RegistrationRepository.get_registration(session)
    if @registration.present?
      @search_query = SearchQuery.new
      render :show
    else
      search_form
    end
  end

  # renders the search form
  def search_form
    @search_query ||= SearchQuery.new(params[:search_query])
    @search_query.lookup_type = 'vid'
    render :show
  end

  # searches for the record and shows status
  def search
    @search_query = SearchQuery.new(params[:search_query])
    return search_form unless @search_query.valid?

    @registration = RegistrationSearch.perform(@search_query)
    RegistrationRepository.store_registration(session, @registration)

    render :show
  rescue RegistrationSearch::SearchError => @error
    search_form
  end

end

app/views/status/_errors.html.haml
- if @error.present?
  %section#errors
    .alert.alert-error= @error.message

app/views/status/_record.html.haml
- if @registration.present?
  - r = @registration
  - p = RegistrationDetailsPresenter.new(r)

  %section#record
    %label Name
    .name
      = r.full_name

    %label Registration address
    .reg_address
      = p.registration_address

    %label Your status
    .voter_status
      = t "voting_status.#{p.status}"

    %label Voting location
    .voting_location
      = p.voting_location

    %label Directions
    - saddr = CGI::escape(p.registration_address)
    - daddr = CGI::escape(p.voting_location_for_directions)
    = link_to "Google maps", "http://maps.google.com/maps?saddr=#{saddr}&daddr=#{daddr}", class: 'directions'

app/views/status/_search.html.haml
%section#search
  = link_to "#", class: 'new_lookup' do
    %i.icon-search
    New lookup

  = form_for @search_query, url: status_path do |f|
    = f.hidden_field :lookup_type

    .partition
      .row
        .span3.numbers
          %label( for='search_query_voter_id' ) Voter ID
          = f.text_field :voter_id, label: 'Voter ID', placeholder: 'NNNNNNNNN', maxlength: 9, class: 'span3'
        .span3
          %label( for='locality_vid' ) Locality
          = f.select :locality, Office.localities, { include_blank: true }, id: 'locality_vid', class: 'span3'

    .row
      .span10
        = f.submit 'Lookup record', class: 'btn'

app/views/status/show.html.haml
- @page_id = 'status'

.row{ class: @registration.blank? ? 'no-reg' : nil }
  .span8.offset1
    .page-header
      %h1 Status Check

    = render 'errors'
    = render 'search'
    = render 'record'