config/routes.rb
VaVote::Application.routes.draw do

  # Add localized scope if alternate localizations are present,
  # otherwise directly add unprefixed routes.
  def conditional_scope(localized_route, root_url, &block)
    unless AppConfig['SupportedLocalizations'].blank?
      scope(localized_route, &block)
      get '/' => root_url # Add root_url outside of localized route.
    else
      block.call
    end
  end

  get '/lookup/registration'            => 'lookup#registration'
    
  namespace :api do
    get '/search(.json)' => 'registrations#show', format: 'json'

    namespace :v1, module: nil do
      get '/demo'            => 'voter_reporting#demo', as: 'demo'
      get '/PollingLocation' => 'voter_reporting#polling_location'
      get '/ReportArrive'    => 'voter_reporting#report_arrive'
      get '/ReportComplete'  => 'voter_reporting#report_complete'
      get '/WaitTimeInfo'    => 'voter_reporting#wait_time_info'
    end
  end



  root_url = AppConfig['demo'] ? 'pages#demo_splash' : "pages#front"
  conditional_scope "/:locale", root_url do

    get   '/not_found'                    => 'pages#not_found', as: 'not_found'

    get   '/registration/new/privacy'     => 'pages#privacy', defaults: { path: 'new_registration' }, as: 'new_registration_privacy'
    get   '/registration/edit/privacy'    => 'pages#privacy', defaults: { path: 'edit_registration' }, as: 'edit_registration_privacy'
    get   '/registration/request_absentee/privacy' => 'pages#privacy', defaults: { path: 'request_absentee_registration' }, as: 'request_absentee_registration_privacy'
    get   '/register/residential/privacy' => 'pages#privacy', defaults: { path: 'register_residential' }, as: 'register_residential_privacy'
    get   '/register/overseas/privacy'    => 'pages#privacy', defaults: { path: 'register_overseas' }, as: 'register_overseas_privacy'

    get   '/search'                       => 'search#new', as: 'search_form'
    get   '/search/unavailable'           => 'search#unavailable'
    post  '/search'                       => 'search#create', as: 'search'

    get   '/register/residential'         => 'registrations#new', defaults: { residence: 'in' }, as: 'register_residential'
    get   '/register/overseas'            => 'registrations#new', defaults: { residence: 'outside' }, as: 'register_overseas'

    get   '/status'                       => 'status#show', as: 'status'
    post  '/status'                       => 'status#search'

    resource :page, only: [], path: '' do
      member do
        get :front, path: AppConfig['demo'] ? '/front' : ''
        get :help
        get :about
        get :about_update_absentee
        get :contact
        get :faq
        get :elections
        get :security
        get :feedback
        get :about_registration
        get :about_update_absentee
        get :online_ballot_marking
        AppConfig.fetch('HeaderLinks', []).each do |settings|
          get settings["url"]
        end
      end
    end

    resource :registration, except: :destroy do
      get '/edit' => 'registrations#edit'
      get '/request_absentee' => 'registrations#edit', defaults: { request_absentee: true }, as: 'request_absentee'
    end
    resource :absentee_request, only: [:new, :create, :edit, :update] do
      get '/not_available' => 'absentee_requests#not_available'
    end
    get '/voter_card.pdf' => 'voter_cards#show', format: 'pdf', as: 'voter_card'


    get '/lookup/absentee_status_history' => 'lookup#absentee_status_history'
    get '/lookup/my_ballot'               => 'lookup#my_ballot'

    get '/ballot_info/:election_uid'      => 'ballot_info#show', as: 'ballot_info'

    resource :form, only: [] do
      member do
        get :request_absentee_status
      end
    end


    root to: root_url
  end
    
  
  match '*unmatched_route', :to => 'application#raise_not_found!'
  
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  before_filter :requires_registration

  def request_absentee_status
    @req = AbsenteeStatusRequest.new

    # Set defaults
    @req.full_name  = current_registration.full_name
    @req.ssn        = current_registration.ssn
  end

  

end

app/helpers/form_helper.rb
module FormHelper
  def spac
    AppConfig['OVR']['show_privacy_act_page']
  end
  
  

  def identity_field_option_label(field)
    opt_label = identity_field_required?(field) ? "&nbsp;" : I18n.t("identity.optional")
    return "#{I18n.t("identity.#{field}")} <span>#{opt_label}</span>".html_safe
  end

  def link_with_privacy_act_to(label, url, *options)
    if url.is_a?(Hash)
      if url[:action] && spac
        url[:action] = "#{url[:action]}_privacy".to_sym
      end
      url = url_for(url)      
    else
      if spac
        url = "#{url}_privacy".to_sym
      end
    end
    link_to label, url, *options
  end

  # TRUE if online balloting is enabled
  def online_balloting?
    ob = services_config['online_balloting']

    AppConfig[''] &&
    !ob['url'].blank? &&
    !ob['access_token'].blank? &&
    !ob['account_id'].blank?
  end

  def online_ballot_url(r = @registration)
    ob = services_config['online_balloting']
    "#{ob['url']}/?search[vid]=#{r.voter_id}&token=#{ob['access_token']}&account=#{ob['account_id']}"
  end


  # Returns the select tags for the date entry and binds them
  def bound_date(f, field, options = {}, html_options = {})
    dts = ActionView::Helpers::DateTimeSelector.new(Date.today)

    start_year  = options[:start_year] || Date.today.year - 150
    end_year    = options[:end_year] || Date.today.year - 17
    object_name = options[:object_name] || 'registration'

    value   = f.object.send(field)
    month   = value && value.month
    day     = value && value.day
    year    = value && value.year

    months  = options_for_select(12.times.map { |i| [ dts.send(:month_name, i + 1), i + 1 ] }, month)
    days    = options_for_select((1 .. 31).to_a, day)
    years   = options_for_select((start_year .. end_year).to_a.reverse, year)
    jsfield = field.to_s.camelcase(:lower)


    month = select_tag("#{object_name}[#{field}(2i)]", months, html_options.merge('data-bind' => "instantValidation: { accessor: '#{jsfield}Month', attribute: '#{jsfield}', complex: true }", prompt: 'Month', include_blank: false))
    day = select_tag("#{object_name}[#{field}(3i)]", days,   html_options.merge('data-bind' => "instantValidation: { accessor: '#{jsfield}Day', attribute: '#{jsfield}', complex: true }", prompt: 'Day'))
    year = select_tag("#{object_name}[#{field}(1i)]", years,  html_options.merge('data-bind' => "instantValidation: { accessor: '#{jsfield}Year', attribute: '#{jsfield}', complex: true }", prompt: 'Year'))

    format = date_format_for_editors

    mi = format.index('M')
    di = format.index('D')
    yi = format.index('Y')

    output = [nil, nil, nil]
    output[mi] = month
    output[di] = day
    output[yi] = year

    output.join(' ').html_safe
  end

  def date_format_for_editors
    format = config_date_format
    format = format.sub('MM', 'M')
    format = format.sub('DD', 'D')
    format.sub('YYYY', 'Y')
  end

  def config_date_format
    format = AppConfig['date_format']
    valid = ->(v) { v.length == 8 && v.include?('YYYY') && v.include?('MM') && v.include?('DD') }

    if format.nil? || format.empty? || !valid.(format)
      'MMDDYYYY'
    else
      format
    end
  end

  def bound_time(f, field, options = {}, html_options = {})
    object_name = options[:object_name] || 'registration'

    value   = f.object.send(field)
    year    = Date.today.year
    month   = Date.today.month
    day     = Date.today.day
    hour    = value && value.hour
    minute  = value && value.min

    hours   = options_for_select([ nil ] + (0 .. 23).to_a, hour)
    minutes = options_for_select([ nil ] + (0 .. 11).map { |n| [ "#{n * 5}".rjust(2, '0'), n * 5 ] }, minute)
    jsfield = field.to_s.camelcase(:lower)

    [ hidden_field_tag("#{object_name}[#{field}(1i)]", year),
      hidden_field_tag("#{object_name}[#{field}(2i)]", month),
      hidden_field_tag("#{object_name}[#{field}(3i)]", day),
      select_tag("#{object_name}[#{field}(4i)]", hours, html_options.merge('data-bind' => "value: #{jsfield}Hour", class: 'span1' )),
      ":",
      select_tag("#{object_name}[#{field}(5i)]", minutes, html_options.merge('data-bind' => "value: #{jsfield}Minute", class: 'span1' ))
    ].join(' ').html_safe
  end

  # Adds the custom suffix used by the record to the list of standard ones
  def name_suffixes_for(reg)
    suffixes = Dictionaries::NAME_SUFFIXES

    if !reg.suffix.blank? && !suffixes.include?(reg.suffix)
      suffixes = suffixes + [ reg.suffix ]
    end

    suffixes.sort
  end

  def field_line(span, value, label = '&nbsp;', options = {})
    if value == :empty || (options.has_key?(:if) && !options[:if])
      label = value = "&nbsp;".html_safe
    end

    content_tag(:div, [
      content_tag(:div, value, class: 'value'),
      content_tag(:label, label )
    ].join(' ').html_safe, class: "span#{span} line")
  end

  def empty_span(span)
    content_tag(:div, "&nbsp;".html_safe, class: "span#{span}")
  end

  def ac
    AppConfig['autocomplete'] ? 'on' : 'off'
  end

  def office_address(locality)
    address = Office.where(locality: locality).first.try(:address)
    address && "General Registrar\n#{address}".gsub("\n", "<br/>").html_safe
  end

  def party_preference_label
    if AppConfig['collect_absentee_party_preference_only_absentee']
      I18n.t('confirm.rows.party_preference.absentee')
    else
      I18n.t('confirm.rows.party_preference.non_absentee')
    end
  end

end

app/views/forms/request_absentee_status.haml
- @page_title = "Absentee status change request"

.row
  .span16#request_absentee_status
    = twitter_bootstrap_form_for @req, url: request_absentee_status_form_path do |f|

      = f.inputs 'Personal information', id: 'personal_info' do
        = f.text_field :full_name, 'Full name of absentee', readonly: true
        = f.text_field :ssn, 'SSN', readonly: true, class: 'span2'

        = f.toggles 'Registered to vote in *' do
          = f.radio_button :location_type, 'County', :county
          = f.radio_button :location_type, 'City', :city
        = f.text_field :location_name, 'of', placeholder: 'Olympia'

        .actions
          = f.button 'Next &rarr;'.html_safe, class: 'next btn'

      = f.inputs 'Election details', id: 'election' do
        = f.toggles 'Applying to vote in *' do
          = f.radio_button :vote_in, 'General Election or Special Election', :general_or_special
          = f.radio_button :vote_in, 'Democratic Primary', :democratic_primary
          = f.radio_button :vote_in, 'Republican Primary', :republican_primary

        = f.date_select :vote_on, 'to be held on', {}, class: 'small'

        .actions
          = f.button '&larr; Back'.html_safe, class: 'back btn'
          or
          = f.submit 'Submit request', class: 'next primary btn'

app/views/forms/request_absentee_status.html.haml
- @page_title = "Absentee status change request"

.row
  .span16#request_absentee_status
    = twitter_bootstrap_form_for @req, url: request_absentee_status_form_path do |f|

      = f.inputs 'Personal information', id: 'personal_info' do
        = f.text_field :full_name, 'Full name of absentee', readonly: true
        = f.text_field :ssn, 'SSN', readonly: true, class: 'span2'

        = f.toggles 'Registered to vote in *' do
          = f.radio_button :location_type, 'County', :county
          = f.radio_button :location_type, 'City', :city
        = f.text_field :location_name, 'of', placeholder: 'Olympia'

        .actions
          = f.button 'Next', class: 'next bt'

      = f.inputs 'Election details', id: 'election' do
        = f.toggles 'Applying to vote in *' do
          = f.radio_button :vote_in, 'General Election or Special Election', :general_or_special
          = f.radio_button :vote_in, 'Democratic Primary', :democratic_primary
          = f.radio_button :vote_in, 'Republican Primary', :republican_primary

        = f.date_select :vote_on, 'to be held on', {}, class: 'small'

        .actions
          = f.button 'Back', class: 'back bt'
          or
          = f.submit 'Submit request', class: 'next primary bt'